name: reminder
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  freezed: ^1.1.1
  equatable: ^2.0.3
  http: ^0.13.4
  shared_preferences: ^2.0.13
  internet_connection_checker: ^0.0.1+3
  get: ^4.6.1
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  persian_number_utility: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
